"""Central color palette for the login screen."""

# Base palette
COLOR_PRIMARY = "#D91414"
COLOR_SECONDARY = "#F4F1EC"
COLOR_THIRD = "#373636"
COLOR_BACKGROUND = "#F4F1EC"
COLOR_SECOND_BACKGROUND = "#161618"
COLOR_TEXT = "#161618"
COLOR_SUCCESS = "#D91414"
COLOR_ERROR = "#D91414"

# Background and decorative elements
COLOR_TRIANGLE_BACKGROUND = COLOR_SECOND_BACKGROUND
COLOR_HEADER_PRIMARY = COLOR_PRIMARY
COLOR_HEADER_TEXT = COLOR_TEXT
COLOR_CORNER = COLOR_PRIMARY
COLOR_ARTIFACT_PRIMARY = COLOR_BACKGROUND
COLOR_ARTIFACT_SECONDARY = COLOR_SECOND_BACKGROUND
COLOR_ARTIFACT_INACTIVE = COLOR_SECOND_BACKGROUND

# Controls
COLOR_CHOOSE_ACTIVE = COLOR_PRIMARY
COLOR_CHOOSE_TEXT = COLOR_SECONDARY
COLOR_CHOOSE_INACTIVE = COLOR_THIRD
COLOR_FIELD_BACKGROUND = COLOR_SECOND_BACKGROUND
COLOR_FIELD_TEXT = COLOR_BACKGROUND
COLOR_FIELD_BORDER_IDLE = COLOR_SECONDARY
COLOR_ACCOUNT_TOGGLE_DEFAULT = COLOR_BACKGROUND
COLOR_ACCOUNT_TOGGLE_ACTIVE = COLOR_PRIMARY
COLOR_ACCOUNT_PANEL_BACKGROUND = COLOR_SECOND_BACKGROUND
COLOR_ACCOUNT_PANEL_TEXT = COLOR_BACKGROUND
COLOR_ACCESS_BACKGROUND = COLOR_PRIMARY
COLOR_ACCESS_TEXT = COLOR_SECONDARY
COLOR_ACCESS_INACTIVE = COLOR_THIRD

# Login log output
COLOR_LOG_PRIMARY = COLOR_PRIMARY
COLOR_LOG_SECONDARY = COLOR_SECONDARY
COLOR_LOG_SUCCESS = COLOR_SUCCESS
COLOR_LOG_ERROR = COLOR_ERROR
COLOR_LOG_BACKGROUND = COLOR_BACKGROUND
