"""Central color palette for the messenger screen.

Update colors here: messenger widgets either use these values directly or
receive them from ``MessengerInterface``.
"""

# Базовая палитра
COLOR_PRIMARY = "#D91414"
COLOR_SECONDARY = "#F4F1EC"
COLOR_THIRD = "#373636"
COLOR_BACKGROUND = "#F4F1EC"
COLOR_SECOND_BACKGROUND = "#161618"
COLOR_TEXT = "#161618"
COLOR_SUCCESS = "#D91414"
COLOR_ERROR = "#A92B2B"

# Поверхности и состояния
COLOR_PANEL_BACKGROUND = COLOR_BACKGROUND
COLOR_DIVIDER = COLOR_BACKGROUND
COLOR_INPUT_BACKGROUND = COLOR_SECOND_BACKGROUND
COLOR_INPUT_FOCUS = "#959292"
COLOR_SEARCH_BACKGROUND = COLOR_BACKGROUND
COLOR_SEARCH_BORDER = COLOR_BACKGROUND
COLOR_SEARCH_FOCUS = COLOR_PRIMARY
COLOR_SEARCH_TEXT = COLOR_TEXT
COLOR_SEARCH_PLACEHOLDER = COLOR_INPUT_FOCUS
COLOR_CONTACT_BACKGROUND = "#FFFFFF"
COLOR_CONVERSATION_CARD_BACKGROUND = COLOR_PANEL_BACKGROUND
COLOR_CONTACT_BORDER = COLOR_INPUT_FOCUS
COLOR_CONTACT_ONLINE = "#00A843"
COLOR_CONTACT_OFFLINE = "#606060"
COLOR_CONTACT_SECTION_BACKGROUND = COLOR_PANEL_BACKGROUND
COLOR_CONTACT_SECTION_TEXT = COLOR_CONTACT_OFFLINE
COLOR_CONTACT_SECTION_ACTIVE = COLOR_PRIMARY
COLOR_MESSAGE_OUTGOING = "#C53A3A"
COLOR_MESSAGE_PENDING = COLOR_THIRD
COLOR_MESSAGE_INCOMING = COLOR_MESSAGE_PENDING
COLOR_BUTTON_PRESSED = COLOR_THIRD

# Текст и индикаторы
COLOR_MESSAGE_TEXT = "#FFFFFF"
COLOR_CONVERSATION_TITLE = COLOR_PRIMARY
COLOR_TEXT_ON_PRIMARY = COLOR_TEXT
COLOR_TEXT_ON_INCOMING = COLOR_SECONDARY
COLOR_TEXT_ON_SURFACE = COLOR_SECONDARY
COLOR_LOADING_SPINNER = COLOR_PRIMARY

# Вспомогательные элементы
COLOR_SCROLLBAR_TRACK = COLOR_PANEL_BACKGROUND
COLOR_SCROLLBAR_HANDLE = COLOR_THIRD
COLOR_CONTEXT_MENU_BACKGROUND = COLOR_SECOND_BACKGROUND
COLOR_CONTACT_CONTEXT_MENU_BACKGROUND = COLOR_PANEL_BACKGROUND
COLOR_PREVIEW_BACKGROUND = COLOR_INPUT_BACKGROUND
COLOR_VIDEO_THUMBNAIL_BACKGROUND = COLOR_INPUT_BACKGROUND
COLOR_OVERLAY = "#000000"
OVERLAY_OPACITY = 210
COLOR_VIDEO_VIEWER_OVERLAY = "rgba(22, 22, 24, 210)"
COLOR_VIDEO_CONTROLS_BACKGROUND = "rgba(55, 54, 54, 180)"
COLOR_VIDEO_SLIDER_GROOVE = COLOR_THIRD
